### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jwedel** [ramosisw/dotnet-nuget-tree#6]
Hi, I'm getting this in a multi-project solution on solution root:

```
$ dotnet nuget-tree -d 2 .              
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at dotnet.nuget.tree.Command.OptionsCommand.<>c.<GetPackages>b__41_0(XElement e) in /home/runner/work/dotnet-nuget-tree/dotnet-nuget-tree/src/Command/OptionsCommand.cs:line 139
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at dotnet.nuget.tree.Command.OptionsCommand.GetPackages(String fullProjectPath) in /home/runner/work/dotnet-nuget-tree/dotnet-nuget-tree/src/Command/OptionsCommand.cs:line 135
   at dotnet.nuget.tree.Command.OptionsCommand.Parse(String[] args) in /home/runner/work/dotnet-nuget-tree/dotnet-nuget-tree/src/Command/OptionsCommand.cs:line 34
   at dotnet.nuget.tree.Program.Main(String[] args) in /home/runner/work/dotnet-nuget-tree/dotnet-nuget-tree/src/Program.cs:line 43
   at dotnet.nuget.tree.Program.<Main>(String[] args)
```

It works inside one project sub-dir, but nowhere else. It always fails with this exception.

**Comment by ghost** [comment]
Tool fails for CentralPackageVersionManagement, there is already open issue about this.

**Comment by jwedel** [comment]
Duplicate of #2
